# Generated by Django 4.0.1 on 2022-01-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mant',
            new_name='matn',
        ),
    ]
